version: "3"

services:
  python:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - VEGVESEN_API_KEY=${VEGVESEN_API_KEY}
      - VEGVESEN_URL=${VEGVESEN_URL}